[project]
name = "ollama-client"
version = "0.1.0"
description = "A simple web client for using local ollama models."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
]
